spring:
  profiles:
    active: local # default
    group:
      local:  # local, common profile을 그룹지어 함께 어플리케이션 구동
        - common
      prod:   # prod, common profile을 그룹지어 함께 어플리케이션 구동
        - common


---

spring:
  config:
    activate:
      on-profile: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:oracle:thin:@funtripDB_high?TNS_ADMIN=D:\\dev\\Wallet_funtripDB
    username: ADMIN
    password: p.t4zrbAMW.kACE
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 8090



---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:oracle:thin:@funtripDB_high?TNS_ADMIN=/home/ubuntu/funtrip/develop/Wallet_funtripDB
    username: ADMIN
    password: p.t4zrbAMW.kACE
    driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 8091


---

spring:
  config:
    activate:
      on-profile: master
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:oracle:thin:@funtripDB_high?TNS_ADMIN=/home/ubuntu/funtrip/master/Wallet_funtripDB
    username: ADMIN
    password: p.t4zrbAMW.kACE
    driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 8099

