spring:
  profiles:
    active: local # default
    group:
      local:  # local, common profile을 그룹지어 함께 어플리케이션 구동
        - common
      prod:   # prod, common profile을 그룹지어 함께 어플리케이션 구동
        - common

---

spring:
  config:
    activate:
      on-profile: local
server:
  port: 8090

---

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8091


---

spring:
  config:
    activate:
      on-profile: master
server:
  port: 8099
